version: '3.8'
services:
  postgresDB:
    image: postgres:16.4
    container_name: POSTGRES_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432
